WORKDIR /home/Events
COPY requirements.txt ./	COPY requirements.txt ./
COPY events events	COPY events events
COPY app.py config.py app.py ./	
 RUN pip install --trusted-host pypi.python.org -r requirements.txt	RUN pip install --trusted-host pypi.python.org -r requirements.txt
 EXPOSE 80	EXPOSE 80
