FROM python:3.7-alpine

LABEL maintainer="Group-3 - Events"

WORKDIR /home/Events
COPY requirements.txt ./
COPY events events

RUN pip install --trusted-host pypi.python.org -r requirements.txt

EXPOSE 80


CMD [ "python", "events/app.py" ]

